version: "2"
run:
  concurrency: 4
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
<<<<<<< HEAD
    - dogsled
    - exportloopref
=======
    - copyloopvar
    - dogsled
>>>>>>> 63379b8 (chore: update to sdk v0.53.0 (#151))
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
