// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	tenderminttypes "github.com/cometbft/cometbft/proto/tendermint/types"
	types "github.com/cosmos/cosmos-sdk/types"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusKeeper is an autogenerated mock type for the ConsensusKeeper type
type ConsensusKeeper struct {
	mock.Mock
}

// Set provides a mock function with given fields: ctx, cp
func (_m *ConsensusKeeper) Set(ctx types.Context, cp *tenderminttypes.ConsensusParams) {
	_m.Called(ctx, cp)
}

// NewConsensusKeeper creates a new instance of ConsensusKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusKeeper {
	mock := &ConsensusKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
