// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feemarket/feemarket/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the feemarket module's genesis state.
type GenesisState struct {
	// Params are the parameters for the feemarket module. These parameters
	// can be utilized to implement both the base EIP-1559 fee market and
	// and the AIMD EIP-1559 fee market.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// BaseFee is the current base fee. This is denominated in the fee
	// per gas unit.
	BaseFee cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=base_fee,json=baseFee,proto3,customtype=cosmossdk.io/math.Int" json:"base_fee"`
	// LearningRate is the current learning rate.
	LearningRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=learning_rate,json=learningRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"learning_rate"`
	// Utilization contains the current state of the AIMD fee market.
	Utilization BlockUtilization `protobuf:"bytes,4,opt,name=utilization,proto3" json:"utilization"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2180652c84279298, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetUtilization() BlockUtilization {
	if m != nil {
		return m.Utilization
	}
	return BlockUtilization{}
}

// BlockUtilization contains the current state of the AIMD fee market. This
// structure tracks total block utilization within a window of blocks.
type BlockUtilization struct {
	// Window contains a list of the last blocks' utilization
	// values. This is used to calculate the next base fee. This
	// stores the number of units of gas consumed per block.
	Window []uint64 `protobuf:"varint,1,rep,packed,name=window,proto3" json:"window,omitempty"`
	// Index is the index of the current block in the block utilization window.
	Index uint64 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *BlockUtilization) Reset()         { *m = BlockUtilization{} }
func (m *BlockUtilization) String() string { return proto.CompactTextString(m) }
func (*BlockUtilization) ProtoMessage()    {}
func (*BlockUtilization) Descriptor() ([]byte, []int) {
	return fileDescriptor_2180652c84279298, []int{1}
}
func (m *BlockUtilization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockUtilization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockUtilization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockUtilization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockUtilization.Merge(m, src)
}
func (m *BlockUtilization) XXX_Size() int {
	return m.Size()
}
func (m *BlockUtilization) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockUtilization.DiscardUnknown(m)
}

var xxx_messageInfo_BlockUtilization proto.InternalMessageInfo

func (m *BlockUtilization) GetWindow() []uint64 {
	if m != nil {
		return m.Window
	}
	return nil
}

func (m *BlockUtilization) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "feemarket.feemarket.v1.GenesisState")
	proto.RegisterType((*BlockUtilization)(nil), "feemarket.feemarket.v1.BlockUtilization")
}

func init() {
	proto.RegisterFile("feemarket/feemarket/v1/genesis.proto", fileDescriptor_2180652c84279298)
}

var fileDescriptor_2180652c84279298 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0xdb, 0x7b, 0x2b, 0xea, 0x00, 0x89, 0x69, 0x90, 0x54, 0x4c, 0x0a, 0x41, 0x17, 0x4d,
	0x0c, 0x6d, 0x50, 0x97, 0x2e, 0x4c, 0x63, 0x30, 0x24, 0x2e, 0x48, 0x8d, 0x0b, 0xdd, 0x90, 0xa1,
	0x1c, 0xca, 0xa4, 0x74, 0xa6, 0xe9, 0x0c, 0xff, 0x7c, 0x0a, 0x1f, 0x86, 0x17, 0x70, 0xc7, 0x92,
	0xb0, 0x32, 0x2e, 0x88, 0x81, 0x17, 0x31, 0xed, 0x8c, 0x42, 0xf4, 0xb2, 0x3b, 0x67, 0xbe, 0xdf,
	0x7c, 0xe7, 0x7c, 0x39, 0xe8, 0xf9, 0x04, 0x20, 0xc1, 0x59, 0x0c, 0xc2, 0x3b, 0x57, 0x8b, 0xae,
	0x17, 0x01, 0x05, 0x4e, 0xb8, 0x9b, 0x66, 0x4c, 0x30, 0xb3, 0xfe, 0x57, 0x73, 0xcf, 0xd5, 0xa2,
	0xdb, 0xa8, 0x45, 0x2c, 0x62, 0x05, 0xe2, 0xe5, 0x95, 0xa4, 0x1b, 0x4f, 0x42, 0xc6, 0x13, 0xc6,
	0x87, 0x52, 0x90, 0x8d, 0x92, 0x9e, 0x5d, 0x19, 0x97, 0xe2, 0x0c, 0x27, 0x0a, 0x6a, 0x7f, 0xbf,
	0x41, 0x95, 0xf7, 0x72, 0xfe, 0x47, 0x81, 0x05, 0x98, 0x6f, 0x50, 0x49, 0x02, 0x96, 0xde, 0xd2,
	0x9d, 0xf2, 0x4b, 0xdb, 0xbd, 0x7b, 0x1f, 0x77, 0x50, 0x50, 0xbe, 0xb1, 0x3d, 0x34, 0xb5, 0x40,
	0xfd, 0x31, 0x7b, 0xe8, 0xc1, 0x08, 0x73, 0x18, 0x4e, 0x00, 0xac, 0x9b, 0x96, 0xee, 0x3c, 0xf4,
	0x5f, 0xe4, 0xfa, 0xcf, 0x43, 0xf3, 0xb1, 0xdc, 0x8d, 0x8f, 0x63, 0x97, 0x30, 0x2f, 0xc1, 0x62,
	0xea, 0xf6, 0xa9, 0xd8, 0x6f, 0x3a, 0x48, 0x2d, 0xdd, 0xa7, 0x22, 0xb8, 0x9f, 0x7f, 0xee, 0x01,
	0x98, 0x9f, 0x51, 0x75, 0x06, 0x38, 0xa3, 0x84, 0x46, 0xc3, 0x0c, 0x0b, 0xb0, 0x6e, 0x0b, 0xb3,
	0xd7, 0xca, 0xec, 0xe9, 0xff, 0x66, 0x1f, 0x20, 0xc2, 0xe1, 0xfa, 0x1d, 0x84, 0xfb, 0x4d, 0xa7,
	0xaa, 0x2c, 0xe5, 0x5b, 0x50, 0xf9, 0x63, 0x15, 0xe4, 0x01, 0x07, 0xa8, 0x3c, 0x17, 0x64, 0x46,
	0xbe, 0x62, 0x41, 0x18, 0xb5, 0x8c, 0x22, 0xa5, 0x73, 0x2d, 0xa5, 0x3f, 0x63, 0x61, 0xfc, 0xe9,
	0xcc, 0xab, 0xbc, 0x97, 0x16, 0xed, 0xb7, 0xe8, 0xd1, 0xbf, 0x98, 0x59, 0x47, 0xa5, 0x25, 0xa1,
	0x63, 0xb6, 0xb4, 0xf4, 0xd6, 0xad, 0x63, 0x04, 0xaa, 0x33, 0x6b, 0xe8, 0x1e, 0xa1, 0x63, 0x58,
	0x15, 0x73, 0x8d, 0x40, 0x36, 0x7e, 0x7f, 0x7b, 0xb4, 0xf5, 0xdd, 0xd1, 0xd6, 0x7f, 0x1d, 0x6d,
	0xfd, 0xdb, 0xc9, 0xd6, 0x76, 0x27, 0x5b, 0xfb, 0x71, 0xb2, 0xb5, 0x2f, 0x5e, 0x44, 0xc4, 0x74,
	0x3e, 0x72, 0x43, 0x96, 0x78, 0x3c, 0x26, 0x69, 0x27, 0x81, 0xc5, 0xc5, 0x39, 0x57, 0x17, 0xb5,
	0x58, 0xa7, 0xc0, 0x47, 0xa5, 0xe2, 0xae, 0xaf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x97, 0x9c,
	0xde, 0x0a, 0x6d, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Utilization.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.LearningRate.Size()
		i -= size
		if _, err := m.LearningRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.BaseFee.Size()
		i -= size
		if _, err := m.BaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *BlockUtilization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockUtilization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockUtilization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Window) > 0 {
		dAtA4 := make([]byte, len(m.Window)*10)
		var j3 int
		for _, num := range m.Window {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintGenesis(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BaseFee.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.LearningRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Utilization.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *BlockUtilization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Window) > 0 {
		l = 0
		for _, e := range m.Window {
			l += sovGenesis(uint64(e))
		}
		n += 1 + sovGenesis(uint64(l)) + l
	}
	if m.Index != 0 {
		n += 1 + sovGenesis(uint64(m.Index))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LearningRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LearningRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utilization", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Utilization.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockUtilization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockUtilization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockUtilization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Window = append(m.Window, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGenesis
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGenesis
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Window) == 0 {
					m.Window = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Window = append(m.Window, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Window", wireType)
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
