// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/cosmos/gogoproto/proto"

	types "github.com/cosmos/cosmos-sdk/types"
)

// FeeGrantKeeper is an autogenerated mock type for the FeeGrantKeeper type
type FeeGrantKeeper struct {
	mock.Mock
}

// UseGrantedFees provides a mock function with given fields: ctx, granter, grantee, fee, msgs
func (_m *FeeGrantKeeper) UseGrantedFees(ctx context.Context, granter types.AccAddress, grantee types.AccAddress, fee types.Coins, msgs []proto.Message) error {
	ret := _m.Called(ctx, granter, grantee, fee, msgs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, types.AccAddress, types.Coins, []proto.Message) error); ok {
		r0 = rf(ctx, granter, grantee, fee, msgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFeeGrantKeeper interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeeGrantKeeper creates a new instance of FeeGrantKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeeGrantKeeper(t mockConstructorTestingTNewFeeGrantKeeper) *FeeGrantKeeper {
	mock := &FeeGrantKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
