// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feemarket/eip1559/v1/feemarket.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EIP1559 is the contains the Additive Increase Multiplicative Decrease
// (AIMD) EIP-1559 fee market parameters and state. This can be utilized
// to implement AIMD EIP-1559 and legacy EIP-1559 fee market.
type EIP1559 struct {
	// Params are the parameters of the AIMD fee market.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// State is the current state of the AIMD fee market.
	State State `protobuf:"bytes,2,opt,name=state,proto3" json:"state"`
}

func (m *EIP1559) Reset()         { *m = EIP1559{} }
func (m *EIP1559) String() string { return proto.CompactTextString(m) }
func (*EIP1559) ProtoMessage()    {}
func (*EIP1559) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0302a7036189a04, []int{0}
}
func (m *EIP1559) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EIP1559) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EIP1559.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EIP1559) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EIP1559.Merge(m, src)
}
func (m *EIP1559) XXX_Size() int {
	return m.Size()
}
func (m *EIP1559) XXX_DiscardUnknown() {
	xxx_messageInfo_EIP1559.DiscardUnknown(m)
}

var xxx_messageInfo_EIP1559 proto.InternalMessageInfo

func (m *EIP1559) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *EIP1559) GetState() State {
	if m != nil {
		return m.State
	}
	return State{}
}

// State contains the current state of the AIMD fee market.
type State struct {
	// BaseFee is the current base fee. This is denominated in the fee
	// per gas unit.
	BaseFee cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=base_fee,json=baseFee,proto3,customtype=cosmossdk.io/math.Int" json:"base_fee"`
	// LearningRate is the current learning rate.
	LearningRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=learning_rate,json=learningRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"learning_rate"`
	// BlockUtilizationWindow contains a list of the last blocks' utilization
	// values. This is used to calculate the next base fee.
	BlockUtilizationWindow []uint64 `protobuf:"varint,3,rep,packed,name=block_utilization_window,json=blockUtilizationWindow,proto3" json:"block_utilization_window,omitempty"`
	// TargetBlockUtilization is the target block utilization.
	TargetBlockUtilization uint64 `protobuf:"varint,4,opt,name=target_block_utilization,json=targetBlockUtilization,proto3" json:"target_block_utilization,omitempty"`
	// MaxBlockUtilization is the maximum block utilization.
	MaxBlockUtilization uint64 `protobuf:"varint,5,opt,name=max_block_utilization,json=maxBlockUtilization,proto3" json:"max_block_utilization,omitempty"`
	// Index is the index of the current block in the block utilization window.
	Index uint64 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0302a7036189a04, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_State.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return m.Size()
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetBlockUtilizationWindow() []uint64 {
	if m != nil {
		return m.BlockUtilizationWindow
	}
	return nil
}

func (m *State) GetTargetBlockUtilization() uint64 {
	if m != nil {
		return m.TargetBlockUtilization
	}
	return 0
}

func (m *State) GetMaxBlockUtilization() uint64 {
	if m != nil {
		return m.MaxBlockUtilization
	}
	return 0
}

func (m *State) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*EIP1559)(nil), "feemarket.eip1559.v1.EIP1559")
	proto.RegisterType((*State)(nil), "feemarket.eip1559.v1.State")
}

func init() {
	proto.RegisterFile("feemarket/eip1559/v1/feemarket.proto", fileDescriptor_b0302a7036189a04)
}

var fileDescriptor_b0302a7036189a04 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6a, 0x13, 0x51,
	0x14, 0xc6, 0x33, 0x6d, 0x92, 0xda, 0xab, 0xdd, 0x8c, 0xa9, 0x8c, 0xad, 0x4c, 0x63, 0x71, 0x51,
	0x90, 0xcc, 0x90, 0x68, 0x51, 0xbb, 0x11, 0x06, 0x0d, 0x04, 0x14, 0xca, 0x88, 0x48, 0xdd, 0x0c,
	0x37, 0x93, 0xd3, 0xe9, 0x25, 0x73, 0xef, 0x1d, 0x66, 0x6e, 0xd2, 0xd4, 0xa7, 0xf0, 0x59, 0x24,
	0x0f, 0x51, 0x5c, 0x95, 0xae, 0xc4, 0x45, 0x91, 0x64, 0xe3, 0x63, 0xc8, 0xfd, 0xd3, 0x26, 0x98,
	0xd9, 0x9d, 0x73, 0xbe, 0xef, 0xf7, 0xcd, 0x99, 0xcb, 0x41, 0xcf, 0x4e, 0x01, 0x28, 0xce, 0x87,
	0x20, 0x7c, 0x20, 0x59, 0xfb, 0xf0, 0xf0, 0x8d, 0x3f, 0x6e, 0xfb, 0x77, 0x43, 0x2f, 0xcb, 0xb9,
	0xe0, 0x76, 0x63, 0x31, 0x30, 0x2e, 0x6f, 0xdc, 0xde, 0x79, 0x1c, 0xf3, 0x82, 0xf2, 0x22, 0x52,
	0x1e, 0x5f, 0x37, 0x1a, 0xd8, 0x69, 0x24, 0x3c, 0xe1, 0x7a, 0x2e, 0x2b, 0x33, 0x7d, 0x5a, 0xfa,
	0xb1, 0x0c, 0xe7, 0x98, 0x1a, 0x70, 0xff, 0x87, 0x85, 0x36, 0xde, 0xf7, 0x8e, 0xa5, 0x66, 0x1f,
	0xa1, 0xba, 0xd6, 0x1c, 0xab, 0x69, 0x1d, 0xdc, 0xef, 0x3c, 0xf1, 0xca, 0xd6, 0xf0, 0x8e, 0x95,
	0x27, 0xa8, 0x5e, 0xde, 0xec, 0x55, 0x42, 0x43, 0xd8, 0xaf, 0x50, 0xad, 0x10, 0x58, 0x80, 0xb3,
	0xa6, 0xd0, 0xdd, 0x72, 0xf4, 0x93, 0xb4, 0x18, 0x52, 0xfb, 0x8f, 0x3a, 0x3f, 0xa7, 0xad, 0x25,
	0xf3, 0xa2, 0x1a, 0xb7, 0xbd, 0x2e, 0xc0, 0x47, 0xd5, 0xf4, 0x68, 0x96, 0x02, 0x05, 0x26, 0xb0,
	0x20, 0x9c, 0xed, 0xff, 0x5d, 0x43, 0x35, 0x15, 0x65, 0x77, 0xd1, 0xbd, 0x3e, 0x2e, 0x20, 0x3a,
	0x05, 0x50, 0x4b, 0x6f, 0x06, 0xcf, 0x65, 0xf8, 0xef, 0x9b, 0xbd, 0x6d, 0xfd, 0x3e, 0xc5, 0x60,
	0xe8, 0x11, 0xee, 0x53, 0x2c, 0xce, 0xbc, 0x1e, 0x13, 0xd7, 0xd3, 0x16, 0x32, 0x0f, 0xd7, 0x63,
	0x22, 0xdc, 0x90, 0x70, 0x17, 0xc0, 0x3e, 0x41, 0x5b, 0x29, 0xe0, 0x9c, 0x11, 0x96, 0x44, 0xf9,
	0xed, 0x6f, 0x6c, 0x06, 0x2f, 0x4d, 0xd8, 0xee, 0x6a, 0xd8, 0x07, 0x48, 0x70, 0x7c, 0xf1, 0x0e,
	0xe2, 0xeb, 0x69, 0x6b, 0xcb, 0x44, 0xea, 0x59, 0xf8, 0xe0, 0x36, 0x2a, 0x94, 0x2b, 0xbe, 0x46,
	0x4e, 0x3f, 0xe5, 0xf1, 0x30, 0x1a, 0x09, 0x92, 0x92, 0x6f, 0xea, 0x0f, 0xa2, 0x73, 0xc2, 0x06,
	0xfc, 0xdc, 0x59, 0x6f, 0xae, 0x1f, 0x54, 0xc3, 0x47, 0x4a, 0xff, 0xbc, 0x90, 0xbf, 0x28, 0x55,
	0x92, 0x02, 0xe7, 0x09, 0x88, 0x68, 0x25, 0xc0, 0xa9, 0x36, 0x2d, 0x49, 0x6a, 0x3d, 0xf8, 0x8f,
	0xb7, 0x3b, 0x68, 0x9b, 0xe2, 0x49, 0x09, 0x56, 0x53, 0xd8, 0x43, 0x8a, 0x27, 0x2b, 0x4c, 0x03,
	0xd5, 0x08, 0x1b, 0xc0, 0xc4, 0xa9, 0x2b, 0x8f, 0x6e, 0x82, 0x93, 0xcb, 0x99, 0x6b, 0x5d, 0xcd,
	0x5c, 0xeb, 0xcf, 0xcc, 0xb5, 0xbe, 0xcf, 0xdd, 0xca, 0xd5, 0xdc, 0xad, 0xfc, 0x9a, 0xbb, 0x95,
	0xaf, 0x6f, 0x13, 0x22, 0xce, 0x46, 0x7d, 0x2f, 0xe6, 0xd4, 0x2f, 0x86, 0x24, 0x6b, 0x51, 0x18,
	0x2f, 0x0e, 0xd9, 0x9f, 0x2c, 0xd5, 0x59, 0x3a, 0x4a, 0x08, 0x2b, 0xee, 0x8e, 0x50, 0x5c, 0x64,
	0x50, 0xf4, 0xeb, 0xea, 0x02, 0x5f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x4c, 0xfc, 0xf5,
	0x13, 0x03, 0x00, 0x00,
}

func (m *EIP1559) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EIP1559) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EIP1559) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *State) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *State) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *State) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintFeemarket(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxBlockUtilization != 0 {
		i = encodeVarintFeemarket(dAtA, i, uint64(m.MaxBlockUtilization))
		i--
		dAtA[i] = 0x28
	}
	if m.TargetBlockUtilization != 0 {
		i = encodeVarintFeemarket(dAtA, i, uint64(m.TargetBlockUtilization))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BlockUtilizationWindow) > 0 {
		dAtA4 := make([]byte, len(m.BlockUtilizationWindow)*10)
		var j3 int
		for _, num := range m.BlockUtilizationWindow {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintFeemarket(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.LearningRate.Size()
		i -= size
		if _, err := m.LearningRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BaseFee.Size()
		i -= size
		if _, err := m.BaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintFeemarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeemarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EIP1559) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	l = m.State.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	return n
}

func (m *State) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BaseFee.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	l = m.LearningRate.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	if len(m.BlockUtilizationWindow) > 0 {
		l = 0
		for _, e := range m.BlockUtilizationWindow {
			l += sovFeemarket(uint64(e))
		}
		n += 1 + sovFeemarket(uint64(l)) + l
	}
	if m.TargetBlockUtilization != 0 {
		n += 1 + sovFeemarket(uint64(m.TargetBlockUtilization))
	}
	if m.MaxBlockUtilization != 0 {
		n += 1 + sovFeemarket(uint64(m.MaxBlockUtilization))
	}
	if m.Index != 0 {
		n += 1 + sovFeemarket(uint64(m.Index))
	}
	return n
}

func sovFeemarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeemarket(x uint64) (n int) {
	return sovFeemarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EIP1559) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeemarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EIP1559: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EIP1559: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeemarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeemarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *State) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeemarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: State: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: State: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LearningRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LearningRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowFeemarket
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.BlockUtilizationWindow = append(m.BlockUtilizationWindow, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowFeemarket
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthFeemarket
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthFeemarket
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.BlockUtilizationWindow) == 0 {
					m.BlockUtilizationWindow = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowFeemarket
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.BlockUtilizationWindow = append(m.BlockUtilizationWindow, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockUtilizationWindow", wireType)
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBlockUtilization", wireType)
			}
			m.TargetBlockUtilization = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetBlockUtilization |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBlockUtilization", wireType)
			}
			m.MaxBlockUtilization = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBlockUtilization |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeemarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeemarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeemarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeemarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeemarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeemarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeemarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeemarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeemarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeemarket = fmt.Errorf("proto: unexpected end of group")
)
